trigger: none

pool:
  vmImage: 'windows-2022'

variables:
- group: mako-iot-github
- name: packageName
  value: 'MakoIoT.Device.Utilities.TimeZones'

resources:
  repositories:
    - repository: templates
      type: github
      name: CShark-Hub/Mako-IoT.Tools
      endpoint: CShark-Hub

steps:
- template: azure-pipelines-templates/azure-pipelines-publish-template.yml@templates